---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
       containers:
         - name: cal-app
           image: us-central1-docker.pkg.dev/sam-474404/java/sam-474404/java:latest 
           ports:
             - containerPort: 8085
---

apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: LoadBalancer
  selector:
    app: app1
  ports:
    - port: 80
      targetPort: 8085




        
